### PR TITLE
Version 3.0

### PR DESCRIPTION
**Pull request by mika-f**
This PR includes that following changes:

* Support to `*.vrm` (#34)
* Support to modern importers in OBJ and STL (#38)
* Support to configure import settings when dropped file

### CODE REVIEW

**Comment by fire** [comment]
Let me know when you are ok to test.

**Comment by mika-f** [comment]
> Let me know when you are ok to test. Can you sketch a test plan?

Ok. When the next version has a decent amount of features, I'll send a mention in the comments section of this PR.
If no bugs are found for about a week, I'm thinking of releasing it to the general public.

**Comment by dest1yo** [comment]
Can't wait to experience version 3.0

**Comment by mika-f** [comment]
This PR has been released as alpha version!

https://github.com/mika-f/blender-drag-and-drop/releases/tag/v3.0.0-alpha.2

I will be worked on other Pull Request for bugs that have already known and feedbacks.

**Comment by dest1yo** [comment]
I'm using the test version and I found 2 problems
The first one may just happen occasionally when I enable the plug-in for the first time and it will show that it cannot find the `operator.DropEventListener` in the `init.py`'s code line: `classes: list[type] = [operator.DropEventListener, preferences.DragAndDropPreferences]`. So I unconditionally `from . import operator` in the init file, and then the plug-in can be enabled and work normally. But after I reverted back to the original code, the previous problem did not reappear.
The second question is:
After dragging in the file, the import menu will be displayed three times.
I've restarted blender and restarted the plug-in, and it's still like this

Other than that everything works great. I've also tried adding a custom format import with no issues at all. Thank you for your work

**Pull request merged**
