### PR TITLE
Add support for Blender 3.6.7 ~3.6.14

### PR DESCRIPTION
**Pull request by AoiKamishiro**
I have added a pattern to support Blender 3.6.7 LTS to Blender 3.6.14 LTS.
I have confirmed that models in FBX format can be imported in D&D in each version of Blender.
Note: The Blender 3.6.6 LTS release was skipped, so I have not added the pattern.

### CODE REVIEW

**Comment by AoiKamishiro** [comment]
Sorry, I created a branch from the main branch, so I created a request in the develop branch to include the other parts of the project I worked on.
Please let me know if there is a problem and I will re-create the request.

**Comment by mika-f** [comment]
Thank you for your contributing!
Can you clean commit history?
I would be happy if you could use Cherry-Pick or similar to pick up only the commit history that corresponds to the differences from `develop` branch.

**Comment by AoiKamishiro** [comment]
Alright!
I changed the branch derivation source from main to develop and cleaned it up!

**Review by mika-f — APPROVED** [review]

**Comment by mika-f** [comment]
Thanks! I merge the PR, and will release next version at the today!

**Comment by mika-f** [comment]
@AoiKamishiro 
Can you link the email address associated with making commits to your GitHub account? I think this would be beneficial as it would show up in the contributor column, commit history, and etc (though not required).

image

**Comment by AoiKamishiro** [comment]
Thanks!
I just now linked the email address I used for the commit to GitHub!

**Pull request merged**
